name: React build apple

on:
  push:
    branches:
      - dev-hsh-ssh

jobs:
  React-Build-ssh-action:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 3m
          script: |
            whoami

      - name: Test Set State
        run: echo "{NOW}={$(date +'%y.%m.%d')}" >> $GITHUB_STATE

      - name: Test Get State
        run: echo "$NOW"