name: React build apple

######### master branch에 push 되었을때만 실행#########
on: 
  push:            
    branches:
      - dev-hsh-ssh
######### master branch에 push 되었을때만 실행#########

jobs:
  React-Build-ssh-action:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          timeout: 3m
          script: |
            whoami
            echo "테스트 출력"
            cd docker
            bash deploy.sh